### ISSUE TITLE
პროექტის სტრუქტურა

### ISSUE THREAD

**Issue by jibla** [kobakareli/FreeUni-Swift-2015-Final-Project---Driving-License-Theory-App#1]
- AppDelegate ფაილის გატანა Supporting Files-ში
- გააკეთეთ ფოლდერი ViewControllers და იმაში გადაიტანეთ ყველა ვიუ კონტროლერი
- ასევე წინასწარ გააკეთეთ ცალკე ფოლდერი Views, რომელშიც custom ვიუების ფაილები გექნებათ.
- იგივე ეხება მოდელებს (კლასები, სტრუქტურები ეტც)

პ.ს. ეს თიქეთი არ დავხუროთ ბოლომდე და თუ რამე იქნება კომენტარებში დავწეროთ კიდევ.

**Comment by TMandzu** [comment]
მასტერზეა საბოლოო ვერსია :)
